-- ============================================
-- SQL SALES DATA ANALYSIS PROJECT
-- ============================================
-- Dataset: orders
-- Purpose:
-- Analyze sales performance, customer behavior,
-- referral sources, payment methods, coupons,
-- and revenue trends using SQL queries.
-- ============================================



-- ============================================
-- 1. TOTAL REVENUE
-- ============================================
-- Calculates total revenue generated from all orders

SELECT SUM(TotalPrice) AS TotalRevenue
FROM orders;



-- ============================================
-- 2. REVENUE BY PRODUCT
-- ============================================
-- Shows total revenue generated by each product

SELECT
    Product,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY Product
ORDER BY Revenue DESC;



-- ============================================
-- 3. ORDERS BY PAYMENT METHOD
-- ============================================
-- Counts total number of orders by payment method

SELECT
    PaymentMethod,
    COUNT(OrderID) AS Orders
FROM orders
GROUP BY PaymentMethod
ORDER BY Orders DESC;



-- ============================================
-- 4. TOP 10 CUSTOMERS BY REVENUE
-- ============================================
-- Identifies highest-value customers based on revenue

SELECT
    CustomerID,
    COUNT(OrderID) AS Orders,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY CustomerID
ORDER BY Revenue DESC
LIMIT 10;



-- ============================================
-- 5. TOTAL ORDERS BY ORDER STATUS
-- ============================================
-- Displays number of orders for each order status

SELECT
    OrderStatus,
    COUNT(OrderID) AS TotalOrders
FROM orders
GROUP BY OrderStatus
ORDER BY TotalOrders DESC;



-- ============================================
-- 6. REVENUE BY REFERRAL SOURCE
-- ============================================
-- Shows revenue contribution from each referral source

SELECT
    ReferralSource,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY ReferralSource
ORDER BY Revenue DESC;



-- ============================================
-- 7. REVENUE BY PAYMENT METHOD
-- ============================================
-- Displays total revenue generated by payment methods

SELECT
    PaymentMethod,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY PaymentMethod
ORDER BY Revenue DESC;



-- ============================================
-- 8. AVERAGE ORDER VALUE BY PAYMENT METHOD
-- ============================================
-- Calculates average customer spending for each payment method

SELECT
    PaymentMethod,
    COUNT(OrderID) AS Orders,
    SUM(TotalPrice) AS Revenue,
    ROUND(AVG(TotalPrice), 2) AS AverageOrderValue
FROM orders
GROUP BY PaymentMethod
ORDER BY Revenue DESC;



-- ============================================
-- 9. REVENUE BY COUPON CODE
-- ============================================
-- Shows coupon performance by orders and revenue

SELECT
    CouponCode,
    COUNT(OrderID) AS Orders,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY CouponCode
ORDER BY Revenue DESC;



-- ============================================
-- 10. TOP SELLING PRODUCTS BY QUANTITY
-- ============================================
-- Identifies products with highest quantity sold

SELECT
    Product,
    SUM(Quantity) AS TotalQuantitySold
FROM orders
GROUP BY Product
ORDER BY TotalQuantitySold DESC;



-- ============================================
-- 11. AVERAGE REVENUE PER PRODUCT
-- ============================================
-- Calculates average revenue generated per product

SELECT
    Product,
    ROUND(AVG(TotalPrice), 2) AS AverageRevenue
FROM orders
GROUP BY Product
ORDER BY AverageRevenue DESC;



-- ============================================
-- 12. HIGHEST VALUE ORDERS
-- ============================================
-- Displays top 10 highest-value transactions

SELECT
    OrderID,
    CustomerID,
    Product,
    TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;



-- ============================================
-- 13. REVENUE BY ORDER STATUS
-- ============================================
-- Shows revenue contribution by order status

SELECT
    OrderStatus,
    SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY OrderStatus
ORDER BY Revenue DESC;



-- ============================================
-- 14. TOTAL ORDERS BY REFERRAL SOURCE
-- ============================================
-- Counts total orders generated by referral source

SELECT
    ReferralSource,
    COUNT(OrderID) AS TotalOrders
FROM orders
GROUP BY ReferralSource
ORDER BY TotalOrders DESC;



-- ============================================
-- 15. COUPON USAGE FREQUENCY
-- ============================================
-- Displays how frequently each coupon was used

SELECT
    CouponCode,
    COUNT(*) AS UsageCount
FROM orders
GROUP BY CouponCode
ORDER BY UsageCount DESC;